Add checks for emass.json and format validations
Signed-off-by: Brett Logan <lindluni@github.com>

diff --git a/codeql-analysis/action.yml b/codeql-analysis/action.yml
--- a/codeql-analysis/action.yml
+++ b/codeql-analysis/action.yml
@@ -20,6 +20,40 @@ runs:
     - name: Checkout repository
       uses: actions/checkout@v3
 
+    - name: Validate emass.json
+      if: steps.build-steps.outputs.result != '' && runner.os != 'Windows'
+      shell: bash
+      run: |
+        json_file=".github/emass.json"
+        
+        echo "Validating emass.json"
+        if [ ! -f "$json_file" ]; then
+          echo "Error: emass.json not found, please refer to the OIS documentation on creating the emass.json file"
+          exit 1
+        fi
+        
+        output=$(jq '.' "$json_file" 2> /dev/null)
+        if [ $? -ne 0 ]; then
+          echo "Error: malformed emass.json file, please refer to the OIS documentation on creating the emass.json file"
+          exit 4
+        fi
+
+    - name: Build Source
+      if: steps.build-steps.outputs.result != '' && runner.os == 'Windows'
+      shell: powershell
+      run: |
+        $json_file = ".github\emass.json"
+        
+        Write-Output "Validating .github\emass.json"
+        if (!(Test-Path $json_file)) {
+          Write-Output "Error: .github\emass.json not found, please refer to the OIS documentation on creating the emass.json file"
+          Exit 1
+        }
+        $output = Get-Content $json_file -Raw -ErrorAction SilentlyContinue | ConvertFrom-Json
+        if (!$?) {
+          Write-Output "Error: malformed emass.json file, please refer to the OIS documentation on creating the emass.json file"
+          Exit 4
+        }
     - name: Initialize CodeQL
       uses: github/codeql-action/init@v2
       with:
